version: "4.17"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: postgres_containr
    environment:
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
      POSTGRES_DB: habrdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7.2
    container_name: pgadmin_containr
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@habr.com
      PGADMIN_DEFAULT_PASSWORD: adminpwd
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:
